-- V1__init.sql

CREATE TABLE public.aluno (
    matricula integer NOT NULL,
    data_de_nascimento date NOT NULL,
    nome character varying(255) NOT NULL,
    serie character varying(255) NOT NULL
);

ALTER TABLE public.aluno ALTER COLUMN matricula ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aluno_matricula_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.professor (
    cod_professor integer NOT NULL,
    disciplina character varying(255) NOT NULL,
    nivel_graduacao character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    salario numeric(38,2) NOT NULL,
    telefone character varying(255) NOT NULL
);

ALTER TABLE public.professor ALTER COLUMN cod_professor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.professor_cod_professor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.turma (
    cod_turma integer NOT NULL,
    nome character varying(255) NOT NULL,
    cod_professor_fk integer
);

ALTER TABLE public.turma ALTER COLUMN cod_turma ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.turma_cod_turma_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sala (
    nro_sala integer NOT NULL,
    altura double precision NOT NULL,
    comprimento double precision NOT NULL,
    largura double precision NOT NULL,
    cod_turma_fk integer
);

ALTER TABLE public.sala ALTER COLUMN nro_sala ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sala_nro_sala_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.turmas_alunos (
    aluno_fk integer NOT NULL,
    turma_fk integer NOT NULL
);

-- Primary keys
ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_pkey PRIMARY KEY (matricula);

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT professor_pkey PRIMARY KEY (cod_professor);

ALTER TABLE ONLY public.turma
    ADD CONSTRAINT turma_pkey PRIMARY KEY (cod_turma);

ALTER TABLE ONLY public.sala
    ADD CONSTRAINT sala_pkey PRIMARY KEY (nro_sala);

-- Unique constraints
ALTER TABLE ONLY public.sala
    ADD CONSTRAINT uk_sala_turma UNIQUE (cod_turma_fk);

ALTER TABLE ONLY public.professor
    ADD CONSTRAINT uk_professor_nome UNIQUE (nome);

-- Foreign keys
ALTER TABLE ONLY public.sala
    ADD CONSTRAINT fk_sala_turma FOREIGN KEY (cod_turma_fk) REFERENCES public.turma(cod_turma);

ALTER TABLE ONLY public.turma
    ADD CONSTRAINT fk_turma_professor FOREIGN KEY (cod_professor_fk) REFERENCES public.professor(cod_professor);

ALTER TABLE ONLY public.turmas_alunos
    ADD CONSTRAINT fk_turmas_alunos_aluno FOREIGN KEY (aluno_fk) REFERENCES public.aluno(matricula);

ALTER TABLE ONLY public.turmas_alunos
    ADD CONSTRAINT fk_turmas_alunos_turma FOREIGN KEY (turma_fk) REFERENCES public.turma(cod_turma);